### ISSUE TITLE
README is "wrong"

### ISSUE THREAD

**Issue by jmg-duarte** [danielhenrymantilla/fix_hidden_lifetime_bug.rs#1]
You say "are you getting one of the two following errors" and then show three. Which one is the error?

**Comment by danielhenrymantilla** [comment]
True, I ended up adding a third example, rendering that 'two' obsolete. Fixed in https://github.com/danielhenrymantilla/fix_hidden_lifetime_bug.rs/commit/345a91bbb9904be0e8ccc36c129d22030f555652
