### ISSUE TITLE
"use of moved value" error after using lifetime fix macro

### ISSUE THREAD

**Issue by alisufian** [danielhenrymantilla/fix_hidden_lifetime_bug.rs#5]
Compiling this code
```
use ::fix_hidden_lifetime_bug::fix_hidden_lifetime_bug;

#[fix_hidden_lifetime_bug(showme)]
async fn baz<'a>(a: &'static (), b: &'_ (), url: String) {
    consume(url);
}

fn consume(u: String) {
    println!("{}", u);
}
```
gives the following error

```
error[E0382]: use of moved value: `url`
 --> src/main.rs:9:13
  |
8 | async fn baz<'a>(a: &'static (), b: &'_ (), url: String) {
  |                                             --- value moved here
9 |     consume(url);
  |             ^^^ value used here after move
  |
  = note: move occurs because `url` has type `String`, which does not implement the `Copy` trait
```
Rust 1.53.0
I'm not sure if I'm doing something wrong or its a bug in the lifetime fix itself. The actual code I have works fine until I hit the lifetime bug, trying to fix it with this crate starts giving the value moved error.

Thank you for the crate!

**Comment by danielhenrymantilla** [comment]
Heh, silly me, with my test suite I forgot to check against this real-life use case 🤦

If you use the `showme` feature, you'll see the issue: the instruction to just _mention_ the captured vars actually _moves_ them: the vars need to be borrowed (or rebound). Fix incoming soon, thanks for reporting it!

**Comment by alisufian** [comment]
Works for me now! Thanks for the quick fix. 👍
