### ISSUE TITLE
Can not find attribute `fix_hidden_lifetime_bug` in this scope

### ISSUE THREAD

**Issue by tubzby** [danielhenrymantilla/fix_hidden_lifetime_bug.rs#7]
I'm coming from this thread: https://github.com/rust-lang/rust/issues/63033#issuecomment-874562296

I got a binary crate, the project structure is like this:

```
.
|-- doc
`-- src
    |-- bin
    |-- conn
    |   `-- msg

```
I have main.rs and lib.rs under src, with conn.rs under conn mod. how can I use the macro fix_hidden_lifetime_bug in conn.rs?
I'm using the latest stable channel of rust.

**Comment by danielhenrymantilla** [comment]
I recommend that a `#[macro_use] extern crate fix_hidden_lifetime_bug;` be put at the beginning (that is, before the `mod` declarations) of the `src/lib.rs` and/or `src/main.rs` files.

Another approach is to use `#[::fix_hidden_lifetime_bug::fix_hidden_lifetime_bug]` from anywhere, without needing the `#[macro_use]` declaration 🙂

  - (Obviously, in all cases you need the `fix-hidden-lifetime-bug = "…"` line under the `[dependencies]` section of the `Cargo.toml` file)

___

Note that in your case, from that thread, using `+ 'static` on the trait object fixed the issue, in which case you can skip using this crate / macro altogether.

**Comment by tubzby** [comment]
Hi @danielhenrymantilla , I already add 'static lifetime, but same error message here:

```rust
    async fn read_loop(
        &self,
        st: &mut State,
        s: Box<dyn std::io::Read + 'static>,
        ch: &SendCh,
    ) -> Result<(), Box<dyn Error>> {
```

**Comment by danielhenrymantilla** [comment]
Try with a `+ 'static` on that return type as well 🙂

**Comment by danielhenrymantilla** [comment]
Closing from inactivity: assuming it was fixed.
